- .github/workflows/build-master.yml
- .github/workflows/publish-release.yml
- .github/workflows/stdlib-workflow-trigger.yml
- README.md
$subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Fix build scripts

- websubhub-ballerina/commons.bal
- websubhub-ballerina/http_service.bal
- websubhub-ballerina/utils.bal
> Refactor request to rawRequest

- build.gradle
- gradle.properties
- websubhub-ballerina/tests/basic_hub_test.bal
- websubhub-ballerina/utils.bal
Fixes the subscription & unsubscription method validation failure request. As per the websub spec both validation failure and intent verification should be a get request differentiated by the hub.mode query param
> Fix validation failure callback request

- websubhub-ballerina/http_service.bal
- websubhub-ballerina/init.bal
- websubhub-ballerina/natives.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Change the name of the `java` langlib module to `jballerina.java`

- websubhub-ballerina/Ballerina.toml
- websubhub-ballerina/Dependencies.toml
- websubhub-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
> Add Dependencies.toml

- websubhub-ballerina/commons.bal
- websubhub-ballerina/errors.bal
- websubhub-ballerina/http_service.bal
- websubhub-ballerina/hub_service.bal
- websubhub-ballerina/natives.bal
- websubhub-ballerina/publisher_client.bal
- websubhub-ballerina/tests/basic_hub_test.bal
- websubhub-ballerina/tests/websub_publisher_test.bal
- websubhub-ballerina/utils.bal
- websubhub-native/src/main/java/io/ballerina/stdlib/websubhub/HubNativeOperationHandler.java
> Refactor unregister to deregister

- websubhub-ballerina/Dependencies.toml
> Fix hardcoded versions

- websubhub-ballerina/Dependencies.toml
- websubhub-ballerina/build.gradle
- websubhub-ballerina/commons.bal
- websubhub-ballerina/errors.bal
- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/publisher_client.bal
> Added ```WebSubHub ClientConfiguration``` and updated API documentation.
> Added ClientConfiguration Type for WebSubHub and updated documentation.

- websubhub-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
> Change ballerina archive extension to bala

- README.md
- websubhub-ballerina/Package.md
> Update links and description in Readme.md and Package.md

- websubhub-ballerina/hub_client.bal
> Update crypto-hmac usage to support latest api-change

- .github/workflows/publish-release.yml
- gradle.properties
- websubhub-ballerina/build.gradle
> $subject
Part of [#957](https://github.com/ballerina-platform/ballerina-standard-library/issues/957)
> Enable publishing to ballerina-central and publish websubhub testable-jar

- websubhub-ballerina/build.gradle
> Fix the error when publishing to ballerina central

- websubhub-ballerina/commons.bal
- websubhub-ballerina/http_service.bal
- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/hub_service.bal
- websubhub-ballerina/natives.bal
- websubhub-ballerina/publisher_client.bal
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/tests/hub_with_header_details_test.bal
- websubhub-ballerina/utils.bal
- websubhub-native/src/main/java/io/ballerina/stdlib/websubhub/HubNativeOperationHandler.java
> $subject
Fixes [#1019](https://github.com/ballerina-platform/ballerina-standard-library/issues/1019)
> Include http:Headers parameter to websubhub:Service methods

- websubhub-ballerina/build.gradle
> Remove publishing testable jar and exec artifacts

- .github/workflows/pull-request.yml
> Update Codecov Repor Generation Task in PR

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- build.gradle
- gradle.properties
- websubhub-ballerina/tests/additional_error_details_test.bal
- websubhub-ballerina/tests/basic_hub_test.bal
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/tests/hub_with_header_details_test.bal
- websubhub-ballerina/tests/ssl_enabled_hub_test.bal
> Remove std-lib reflect dependency

- websubhub-ballerina/build.gradle
- websubhub-ballerina/commons.bal
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/utils.bal
> Update http-client usage according to latest api-change

- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/tests/ssl_enabled_hub_client_test.bal
- websubhub-ballerina/tests/test_init.bal
- websubhub-ballerina/tests/utils_test.bal
> Refactor content-distribution-success message generation logic

- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/tests/test_init.bal
- websubhub-ballerina/tests/utils_test.bal
> Fix hub-client content dilevery logic-issue with no http-response content

- codecov.yml
> Remove codecov.yml file

- gradle.properties
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/tests/ssl_enabled_hub_client_test.bal
- websubhub-ballerina/tests/test_init.bal
- websubhub-ballerina/utils.bal
> Fix compilation errors

- build.gradle
- websubhub-ballerina/build.gradle
> Strip stdlib dependency version

- .github/workflows/central-publish.yml
- README.md
- websubhub-ballerina/build.gradle
> $subject
Part of [#1247](https://github.com/ballerina-platform/ballerina-standard-library/issues/1247)
> Move Ballerina build, test and publish into a single task

- websubhub-compiler-plugin-test/build.gradle
> Fix compiler plugin test failure

- websubhub-compiler-plugin-test/src/test/resources/testng.xml
- websubhub-compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/visitor/ListenerInitiationExpressionVisitor.java
> Fix type validation issue with implicit new expressions

- changelog.md
> Update changelog for alpha5 release

- websubhub-compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/AnalyserUtils.java
- websubhub-compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/ServiceAnalysisTask.java
- websubhub-compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/visitor/ListenerInitiationExpressionVisitor.java
>  Refactor compiler plugin validation logic

- websubhub-compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/visitor/ListenerInitiationExpressionVisitor.java
> Fix listener init argument validation for explicit new expressions

- .github/workflows/daily-build.yml
> Fix character encoding issue in websubhub daily build

- websubhub-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
> Set flag to enable Jacoco Coverage XML generation

- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/publisher_client.bal
> Migrate to latest http-client changes

- changelog.md
- settings.gradle
- websubhub-examples/build.gradle
- websubhub-examples/kafka-hub-service/.gitignore
- websubhub-examples/kafka-hub-service/Ballerina.toml
- websubhub-examples/kafka-hub-service/Kafka-Startup-Guide.md
- websubhub-examples/kafka-hub-service/Readme.md
- websubhub-examples/kafka-hub-service/common_util.bal
- websubhub-examples/kafka-hub-service/house_keeping_util.bal
- websubhub-examples/kafka-hub-service/hub_service.bal
- websubhub-examples/kafka-hub-service/init.bal
- websubhub-examples/kafka-hub-service/service_util.bal
> $subject
Related to [#823](https://github.com/ballerina-platform/ballerina-standard-library/issues/823)
Related to [#922](https://github.com/ballerina-platform/ballerina-standard-library/issues/992)
> Include Kafka based WebSubHub Sample

- websubhub-ballerina/Module.md
> Update Module md according to standards

- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/publisher_client.bal
- websubhub-ballerina/tests/basic_hub_test.bal
- websubhub-ballerina/tests/hub_with_error_return_types.bal
- websubhub-ballerina/tests/ssl_enabled_hub_client_test.bal
> $subject
Related to [#423](https://github.com/ballerina-platform/module-ballerina-http/pull/423)
> Sync with HTTP inbound error response update

- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/publisher_client.bal
- websubhub-ballerina/tests/basic_hub_test.bal
- websubhub-ballerina/tests/hub_with_error_return_types.bal
> $subject
This reverts [33a2a28](https://github.com/ballerina-platform/module-ballerina-websubhub/pull/173/commits/33a2a28302f6acaceecd4cab2c5db3710380a322)
Related to [#425](https://github.com/ballerina-platform/module-ballerina-http/pull/425)
> Revert "Sync with HTTP inbound error response update"

- websubhub-ballerina/commons.bal
- websubhub-ballerina/errors.bal
- websubhub-ballerina/http_service.bal
- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/tests/utils_test.bal
> Fix Service Execution error in content-distribution with websub:HubClient

- websubhub-examples/kafka-hub/hub-impl/.gitignore
- websubhub-examples/kafka-hub/hub-impl/Config.toml
- websubhub-examples/kafka-hub/hub-impl/common_util.bal
- websubhub-examples/kafka-hub/hub-impl/house_keeping_util.bal
- websubhub-examples/kafka-hub/hub-impl/hub_persistence.bal
- websubhub-examples/kafka-hub/hub-impl/hub_service.bal
- websubhub-examples/kafka-hub/hub-impl/init.bal
> Add functionality to sync in-memory state with kafka-persistence state

- websubhub-examples/kafka-hub/hub/modules/security/security.bal
- websubhub-examples/kafka-hub/publisher/content_publish_client.bal
> Fix resource paths and update hub URL

- websubhub-examples/kafka-hub/hub/modules/config/configurations.bal
- websubhub-examples/kafka-hub/hub/start_hub.bal
> Update default security config for kafka-hub service

- websubhub-examples/kafka-hub/subscriber/subscriber_service.bal
> Remove service-path from subscriber sample

- websubhub-examples/kafka-hub/README.md
> Fix the typo in README.md

- websubhub-examples/kafka-hub/README.md
- websubhub-examples/kafka-hub/hub/hub_service.bal
- websubhub-examples/kafka-hub/hub/modules/connections/connections.bal
- websubhub-examples/kafka-hub/hub/modules/persistence/persistence.bal
- websubhub-examples/kafka-hub/hub/start_hub.bal
> Refactor kafka-hub example

- websubhub-examples/kafka-hub/hub/start_hub.bal
> Refactor the code

- websubhub-examples/kafka-hub/hub/start_hub.bal
> Add do-on-fail validation to code

- websubhub-examples/kafka-hub/hub/hub_service.bal
- websubhub-examples/kafka-hub/hub/modules/config/configurations.bal
- websubhub-examples/kafka-hub/hub/modules/security/security.bal
This is the implementation of customized MOSIP auth design as in https://github.com/mosip/websub/blob/develop/src/filters/authfilter.bal
> Implement customized mosip auth design

- websubhub-examples/kafka-hub/hub/Config.toml
- websubhub-examples/kafka-hub/hub/modules/config/configurations.bal
> Add default configuration for base IdP URL and token-validate URL

- websubhub-examples/kafka-hub/consolidator/Cloud.toml
- websubhub-examples/kafka-hub/hub/Cloud.toml
- websubhub-examples/kafka-hub/hub/hub_service.bal
> Fix c2c config issues

- websubhub-examples/kafka-hub/hub/Ballerina.toml
> Remove unwanted buil configuration

- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/AnalyserUtils.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/validator/ServiceDeclarationValidator.java
> Fix issues compiler plugin test failure

- .github/workflows/publish-release.yml
- .gitignore
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- build-config/resources/CompilerPlugin.toml
- gradle.properties
$Subject
Related Issue: [#1746](https://github.com/ballerina-platform/ballerina-standard-library/issues/1746)
> Make the Ballerina Project Tooling Friendly

- ballerina/Module.md
> $subject
Fixes [#1903](https://github.com/ballerina-platform/ballerina-standard-library/issues/1903)
> [FIX] Formatting issue in websubhub API docs

- ballerina/Dependencies.toml
- gradle.properties
> $subject
Related to [#1970](https://github.com/ballerina-platform/ballerina-standard-library/issues/1970)
N/A
> Restructure WebSubHub Dependencies

- .github/workflows/build-timestamped-master.yml
$Subject
Related: [#2362](https://github.com/ballerina-platform/ballerina-standard-library/issues/2362)
N/A
> Skip Master Build for `.md` File Changes

- build.gradle
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHttpToWebsubhubAdaptor.java
> $subject
Related to [#2382](https://github.com/ballerina-platform/ballerina-standard-library/issues/2383)
N/A
> Migrate to latests ballerina runtime APIs

- ballerina/hub_listener.bal
- gradle.properties
> $subject
Related to HTTP PR [#719](https://github.com/ballerina-platform/module-ballerina-http/pull/719)
N/A
~- [ ] Linked to an issue~
~- [ ] Updated the changelog~
~- [ ] Added tests~
> Update `websubhub:Listener` to use latest APIs

- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHttpToWebsubhubAdaptor.java
> $subject
Related to [#2383](https://github.com/ballerina-platform/ballerina-standard-library/issues/2383)
N/A
> Add check for service-object isolation

- ballerina/http_service.bal
- ballerina/hub_client.bal
- ballerina/publisher_client.bal
- ballerina/tests/additional_error_details_test.bal
- ballerina/tests/basic_hub_test.bal
- ballerina/tests/hub_annotation_test.bal
- ballerina/tests/hub_authentication_test.bal
- ballerina/tests/hub_client_test.bal
- ballerina/tests/hub_with_error_return_types.bal
- ballerina/tests/hub_with_header_details_test.bal
- ballerina/tests/ssl_enabled_hub_client_test.bal
- ballerina/tests/ssl_enabled_hub_test.bal
- ballerina/tests/test_init.bal
- ballerina/tests/utils_test.bal
> $subject
Related to [#2164](https://github.com/ballerina-platform/ballerina-standard-library/issues/2164)
N/A
> Remove unwanted taint checks

- gradle.properties
$Subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
N/A
> Update gradle-plugin version

- .github/workflows/publish-release.yml
> Resolve merge conflicts

- ballerina/Dependencies.toml
- ballerina/content_distribution.bal
- ballerina/http_service.bal
> Update code-base with http-parseHeader change

- ballerina/Dependencies.toml
- ballerina/build.gradle
- build.gradle
> $subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2436
N/A
> Fix ballerina publish not depending on compiler plugin tests

- examples/kafka-hub/consolidator/Dependencies.toml
- examples/kafka-hub/consolidator/init_consolidator.bal
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/Dependencies.toml
- examples/kafka-hub/hub/hub_service.bal
- examples/kafka-hub/hub/start_hub.bal
- examples/kafka-hub/subscriber/subscriber_service.bal
> Refactor WebSubHub sample

- ballerina/hub_listener.bal
- ballerina/publisher_client.bal
> Fix API Doc issues

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
Related to - https://github.com/ballerina-platform/ballerina-standard-library/issues/2503
N/A
> Upgrade the module and distribution versions

- ballerina/subscription.bal
> [FIX] Issue in unsubscription-verification request

- ballerina/commons.bal
- ballerina/http_service.bal
- ballerina/hub_client.bal
- ballerina/hub_service.bal
> Update API docs

- examples/kafka-hub/subscriber/subscriber_service.bal
> Remove service-path generation from subscriber-service sample

- docs/spec/spec.md
> $subject
Reference PR: https://github.com/ballerina-platform/module-ballerina-http/pull/873
N/A
> Update the introduction of WebSubHub spec

- docs/spec/spec.md
> Add the URL link for issues

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
> $subject
N/A
- ~[ ] Linked to an issue~
- ~[ ] Updated the changelog~
- ~[ ] Added tests~
- ~[ ] Updated the spec~
> Update to 2201.0.1 patch distribution

- build-config/resources/Ballerina.toml
- gradle.properties
> Update to stable lang version `2201.1.0`

- docs/spec/spec.md
> Reformat WebSubHub spec

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Migrate to Ballerina Update 2

- examples/kafka-hub/consolidator/docker/alpine/Dockerfile
- examples/kafka-hub/hub/docker/alpine/Dockerfile
$subject
- https://github.com/wso2-enterprise/cloud-sre-common/issues/188
> Add component docker files

- examples/kafka-hub/consolidator/docker/alpine/Dockerfile
- examples/kafka-hub/hub/docker/alpine/Dockerfile
$subject
- https://github.com/wso2-enterprise/cloud-sre-common/issues/188
> Remove config toml copy

- examples/kafka-hub/consolidator/docker/alpine/Dockerfile
- examples/kafka-hub/hub/docker/alpine/Dockerfile
> Update Docker file

- examples/kafka-hub/hub/Config.toml
> Disable JWT authentication/authorization

- examples/kafka-hub/hub/Config.toml
> $subject
Part of [#3392](https://github.com/ballerina-platform/ballerina-standard-library/issues/3392)
N/A
> Enable HTTP access logs for WebSub hub

- examples/kafka-hub/hub/docker/alpine/Dockerfile
> Enable trace logs for the hub

- examples/kafka-hub/consolidator/consolidator_service.bal
- examples/kafka-hub/consolidator/healthz_service.bal
- examples/kafka-hub/consolidator/init_consolidator.bal
- examples/kafka-hub/hub/docker/alpine/Dockerfile
- examples/kafka-hub/hub/hub_service.bal
- examples/kafka-hub/hub/start_hub.bal
> $subject
Part of [#3392](https://github.com/ballerina-platform/ballerina-standard-library/issues/3392)
N/A
> Add readiness and liveness probes to `hub` and `consolidator`

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> $subject
Related to [#3315](https://github.com/ballerina-platform/ballerina-standard-library/issues/3315)
Part of [#3447](https://github.com/ballerina-platform/ballerina-standard-library/issues/3447)
N/A
> Update dependency versions to support native-image build

- examples/kafka-hub/consolidator/Config.toml
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/hub_service.bal
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/modules/connections/connections.bal
- examples/kafka-hub/hub/modules/persistence/persistence.bal
- examples/kafka-hub/hub/modules/types/types.bal
- examples/kafka-hub/hub/modules/util/event_hub_consumer_group_mapping.bal
- examples/kafka-hub/hub/modules/util/event_hub_mappings.bal
- examples/kafka-hub/hub/modules/util/event_hub_partition_mapping.bal
- examples/kafka-hub/hub/start_hub.bal
> $subject
Fixes [#3467](https://github.com/ballerina-platform/ballerina-standard-library/issues/3467)
N/A
> Include azure event-hub name-space configuration for websub-topic and websub-subscriber mapping

- examples/kafka-hub/consolidator/Config.toml
- examples/kafka-hub/consolidator/modules/config/configurations.bal
- examples/kafka-hub/consolidator/modules/connections/connections.bal
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/modules/connections/connections.bal
- examples/kafka-hub/hub/modules/util/event_hub_consumer_group_mapping.bal
> Refactor azure websubhub codebase

- examples/kafka-hub/consolidator/Config.toml
- examples/kafka-hub/consolidator/modules/config/configurations.bal
- examples/kafka-hub/consolidator/modules/connections/connections.bal
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/resources/namespace-config.json
> Add namespace configuration as a Json

- examples/kafka-hub/consolidator/Config.toml
- examples/kafka-hub/consolidator/modules/config/configurations.bal
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/resources/namespace-1
- examples/kafka-hub/hub/resources/namespace-config.json
- examples/kafka-hub/hub/resources/system-info
> $subject
Fixes [#3489](https://github.com/ballerina-platform/ballerina-standard-library/issues/3489)
N/A
> Add capability to read the namespace connection strings from a secured file

- examples/kafka-hub/consolidator/Config.toml
- examples/kafka-hub/consolidator/resources/system-info
> $subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3467
N/A
> Restructure configurations in consolidator

- README.md
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/Package.md
- build-config/resources/Ballerina.toml
- changelog.md
- docs/spec/spec.md
- gradle.properties
> $subject
Part of [#3463](https://github.com/ballerina-platform/ballerina-standard-library/issues/3463)
N/A
> Update ballerina-lang and ballerina distribution version

- examples/kafka-hub/integration_test_suite/main.bal
> [Azure WebSubHub Test Suite] Add sleeping interval before publishihng content

- examples/kafka-hub/integration_test_suite/Config.toml
> Update integration-test configurations

- examples/kafka-hub/integration_test_suite/main.bal
> Add logs for the integration test-suite

- examples/kafka-hub/integration_test_suite/main.bal
> Fix integration-test percentation calculation

- examples/kafka-hub/consolidator/consolidator_service.bal
- examples/kafka-hub/hub/hub_service.bal
> Add time-stamp information for topic-registrations

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHttpToWebsubhubAdaptor.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
> Fix failing build for type reference support

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update major version due to dist version bump

- examples/kafka-hub/hub/docker/alpine/Dockerfile
Remove trace logs as it is costly and for security reasons.
> Remove trace logs

- docs/spec/spec.md
Fix HTTP client config broken URL.
> Fix client config broken URL

- .github/workflows/update_specs.yml
Change branch from `master` to `main`.
> Change branch from `master` to `main`

- docs/spec/spec.md
Test the workflow branch change.
> Test the workflow branch change

- docs/spec/spec.md
Reverts ballerina-platform/module-ballerina-websubhub#790
> Revert "Test the workflow branch change"

- changelog.md
- native/build.gradle
- native/src/main/java/io/ballerina/stdlib/websubhub/HubCallback.java
> $subject
Fixes: [#4229](https://github.com/ballerina-platform/ballerina-standard-library/issues/4229)
N/A
> [2201.3.x] Terminate the application when there is a panic from within the `websubhub:Service`

- changelog.md
- native/build.gradle
- native/src/main/java/io/ballerina/stdlib/websubhub/HubCallback.java
> $subject
Fixes: [#4229](https://github.com/ballerina-platform/ballerina-standard-library/issues/4229)
N/A
> [2201.4.x] Terminate the application when there is a panic from within the `websubhub:Service`

- ballerina/Dependencies.toml
- gradle.properties
> Update dependency versions for U5

- ballerina/Dependencies.toml
- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHttpToWebsubhubAdaptor.java
This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344
> Fix object getType() API usage

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update std lib versions

- examples/in-memory-hub/hub/Config.toml
- examples/in-memory-hub/hub/start_hub.bal
> Fix in-memory-hub sample not responding to the requests

- gradle.properties
> Update HTTP dependency version

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- .github/workflows/update_specs.yml
- README.md
- ballerina/Ballerina.toml
- build-config/checkstyle/build.gradle
- build-config/resources/Ballerina.toml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
> Migrate to Java 17

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Fix download links

- .github/workflows/central-publish.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
> Update java-version to 17.0.7

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/subscription.bal
- changelog.md
> $subject
Fixes: [#4800](https://github.com/ballerina-platform/ballerina-standard-library/issues/4800)
N/A
> [2201.7.x] [Fix] Additional parameters sent in the subscription request is not properly propagated into the `websubhub:VerifiedSubscription` message

- changelog.md
> Update changelog file

- examples/kafka-hub/load_balancer/lb_service.bal
> Append path segment when forwarding the request

- examples/kafka-hub/A Guide on implementing Websub Hub backed by Kafka Message Broker.md
> Update kafka-hub readme file

- examples/kafka-hub/A Guide on implementing Websub Hub backed by Kafka Message Broker.md
- examples/kafka-hub/publisher/Config.toml
- examples/kafka-hub/publisher/content_publish_client.bal
- examples/kafka-hub/publisher/topic_registration_client.bal
- examples/kafka-hub/subscriber/Config.toml
- examples/kafka-hub/subscriber/subscriber_service.bal
> Refactor security configurations of sample codes

- examples/kafka-hub/A Guide on implementing Websub Hub backed by Kafka Message Broker.md
- examples/kafka-hub/consolidator/Cloud.toml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/load_balancer/Cloud.toml
> Refactor cloud configurations of the deployment

- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/modules/security/security.bal
- examples/kafka-hub/hub/modules/types/types.bal
> Refactor security configurations of the `hub`

- examples/kafka-hub/consolidator/Cloud.toml
- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/load_balancer/Cloud.toml
> Update package cloud configurations

- examples/kafka-hub/hub/start_hub.bal
- examples/kafka-hub/load_balancer/resources/lb-config.json
> Improve hub to retrieve hub-port from environmental variable

- examples/kafka-hub/cp-server/Dockerfile
- examples/kafka-hub/docker-compose.yaml
> Add a dockerfile for a pre-configured kafka-server

- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
> Update cloud config for the hub

- examples/kafka-hub/consolidator/init_consolidator.bal
- examples/kafka-hub/consolidator/modules/config/configurations.bal
- examples/kafka-hub/consolidator/modules/connections/connections.bal
- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/modules/connections/connections.bal
> Add functionality to retrieve the kafka-bootstrap node from the environmental variable

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/AnalyserUtils.java
- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHttpToWebsubhubAdaptor.java
Fixes ballerina-platform/ballerina-standard-library#4910.
> Make some of the Java classes proper utilities

- examples/kafka-hub/docker-compose.yaml
> Update docker-compose configurations

- examples/kafka-hub/consolidator/Cloud.toml
- examples/kafka-hub/consolidator/modules/connections/connections.bal
- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/hub/modules/connections/connections.bal
> Add support for trustore/keystore filename as env-variable

- examples/kafka-hub/consolidator/modules/connections/connections.bal
- examples/kafka-hub/hub/modules/connections/connections.bal
> Log Kafka client truststore/keystore configurations

- examples/kafka-hub/consolidator/modules/connections/connections.bal
> [KafkaHub] Fix build failures

- examples/kafka-hub/consolidator/Cloud.toml
- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
> [KafkaHub] Update docker image versions

- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/hub/websub_topics.bal
> [KafkaHub] Fix logic issue in updating current websub-topics state

- examples/kafka-hub/publisher/Cloud.toml
- examples/kafka-hub/publisher/main.bal
> [KafkaHub] Refactor the code base

- examples/kafka-hub/consolidator/Cloud.toml
- examples/kafka-hub/consolidator/init_consolidator.bal
- examples/kafka-hub/consolidator/modules/config/configurations.bal
- examples/kafka-hub/consolidator/modules/connections/connections.bal
- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/modules/connections/connections.bal
> [KafkaHub] Update logic to statically set the consumer groups for system consumers using env-variables

- examples/kafka-hub/subscriber/Cloud.toml
- examples/kafka-hub/subscriber/subscriber_service.bal
> [KafkaHub] Update subscriber service to retrieve consumer-group from env-variable

- examples/kafka-hub/hub/hub_service.bal
- examples/kafka-hub/hub/modules/util/util.bal
- examples/kafka-hub/hub/websub_subscribers.bal
- examples/kafka-hub/hub/websub_topics.bal
> $subject
Part of: [#5916](https://github.com/ballerina-platform/ballerina-library/issues/5916)
N/A
> [KafkaHub] Remove unwanted sanitization of websub-topic in the `hub`

- examples/kafka-hub/consolidator/modules/util/util.bal
- examples/kafka-hub/consolidator/websub_topics.bal
> $subject
Part of: [#5916](https://github.com/ballerina-platform/ballerina-library/issues/5916)
N/A
> [KafkaHub] Remove unwanted sanitization of websub-topic in the `consolidator`

- examples/kafka-hub/.github/README.md
> Add the symlink for KafkaHub readme

- examples/kafka-hub/.github/_resources
- examples/kafka-hub/A Guide on implementing Websub Hub backed by Kafka Message Broker.md
> Fix broken image links in the Readme

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/process-load-test-result.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trigger-load-tests.yml
- .github/workflows/trivy-scan.yml
> Update the workflow template links

- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/hub/hub_service.bal
- examples/kafka-hub/hub/websub_subscribers.bal
- examples/kafka-hub/subscriber/Cloud.toml
- examples/kafka-hub/subscriber/subscriber_service.bal
> $subject
Related to: [#6332](https://github.com/ballerina-platform/ballerina-library/issues/6332)
N/A
> Update KafkaHub deployment related configurations

- load-tests/in_memory_hub/src/start_hub.bal
> Fix issue with Hub listener not starting properly

- load-tests/in_memory_hub/deployment/deployment-patch.yaml
- load-tests/in_memory_hub/deployment/service.yaml
- load-tests/in_memory_hub/scripts/load_test/Ballerina.toml
- load-tests/in_memory_hub/scripts/load_test/main.bal
- load-tests/in_memory_hub/src/modules/dispatcher/dispatcher.bal
- load-tests/in_memory_hub/src/start_hub.bal
> Update load-test sample with suggestions from runtime team

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update dependency versions for U10

- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/modules/connections/connections.bal
> $subject
Part of: [#7376](https://github.com/ballerina-platform/ballerina-library/issues/7376)
N/A
> Incorporate support to configure maximum messages for consumer polling

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/process-load-test-result.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trigger-load-tests.yml
- .github/workflows/trivy-scan.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/hub_client.bal
> $subject
Related to: [#7400](https://github.com/ballerina-platform/ballerina-library/issues/7400)
N/A
> [2201.9.x] Mark HubClient as isolated

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/process-load-test-result.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trigger-load-tests.yml
- .github/workflows/trivy-scan.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/hub_client.bal
> $subject
Related to: [#7400](https://github.com/ballerina-platform/ballerina-library/issues/7400)
N/A
> [2201.10.x] Mark HubClient as isolated

- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/security/security.bal
> $subject
Fixes: [#7486](https://github.com/ballerina-platform/ballerina-library/issues/7486)
N/A
> Externalize IdP token validation configurations as env-variables

- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websubhub/CompilerPluginTest.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/WebSubHubDiagnosticCodes.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/validator/ServiceDeclarationValidator.java
> $subject
Part of: [#7600](https://github.com/ballerina-platform/ballerina-library/issues/7600)
N/A
> Upate compiler-plugin validations to support dynamic parameter-order in remote methods

- docs/spec/spec.md
> Re-organize the package spec

- examples/kafka-hub/consolidator/consolidator_service.bal
- examples/kafka-hub/hub/hub_service.bal
- examples/kafka-hub/hub/hub_state_update.bal
- examples/kafka-hub/hub/modules/types/types.bal
- examples/kafka-hub/hub/websub_subscribers.bal
> Sync master with latest kafkahub changes

- examples/kafka-hub/hub/modules/config/configurations.bal
- examples/kafka-hub/hub/start_hub.bal
> Allow running the hub without SSL

- examples/kafka-hub/load-tests/publisher/main.bal
> Use HTTP client for publisher load-test
