- websubhub-ballerina/errors.bal
- websubhub-ballerina/hub_listener.bal
- websubhub-ballerina/tests/additional_error_details_test.bal
- websubhub-ballerina/tests/basic_hub_test.bal
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/tests/test_init.bal
- websubhub-ballerina/tests/websub_publisher_test.bal
- websubhub-ballerina/utils.bal
> With this PR there will be support to include additional details to the errors returned from the `websubhub:Service`.
> Now developers can integrate additional details to `websubhub:Service` error responses as follows.
```ballerina
service /websubhub on websubhub:Listener(9091) {
remote function onRegisterTopic(websubhub:TopicRegistration message)
returns websubhub:TopicRegistrationSuccess|websubhub:TopicRegistrationError {
if (message.topic == "https://sub.topic.com") {
websubhub:TopicRegistrationSuccess successResult = {
body: <map<string>>{
isSuccess: "true"
}
};
return successResult;
} else {
return error websubhub:TopicRegistrationError("Topic registration failed!",
headers = { "Content-Encoding" :  "gzip" },
body = { "hub.additional.details": "Feature is not supported in the …
```
> Including additional parameters to Hub error responses

- websubhub-ballerina/Package.md
- websubhub-ballerina/commons.bal
- websubhub-ballerina/http_service.bal
- websubhub-ballerina/hub_client.bal
- websubhub-ballerina/hub_listener.bal
- websubhub-ballerina/publisher_client.bal
- websubhub-ballerina/tests/additional_error_details_test.bal
- websubhub-ballerina/tests/basic_hub_test.bal
- websubhub-ballerina/tests/hub_client_test.bal
- websubhub-ballerina/tests/hub_with_header_details_test.bal
- websubhub-ballerina/tests/ssl_enabled_hub_test.bal
- websubhub-ballerina/tests/test_init.bal
- websubhub-ballerina/tests/utils_test.bal
- websubhub-ballerina/tests/websub_publisher_test.bal
- websubhub-ballerina/utils.bal
> $subject
* Add support for `x-www-form-urlencoded` content delivery with `websubhub:HubClient`.
* Fix `websubhub module` related documentation issues.
* Refactor code-base according to latest guidelines. 
> Usage of `websubhub:HubClient` to deliver `x-www-form-urlencoded` content is as follows.
```ballerina
websubhub:Subscription subscriptionMsg = {
hub: "https://hub.com", 
hubMode: "subscribe", 
hubCallback: "https://sample.subscriber/callback", 
hubTopic: "https://topic.com", 
hubSecret: "secretkey1"
};
websubhub:HubClient hubClientEp = check new(subscriptionMsg);
map<string> publishedContent = {
"query1": "value1",
"query2": "value2"
};
websubhub:ContentDistributionMessage msg = {
contentType: "application/x-www-form-urlencoded",
content: publishedContent
};
var publishResponse = …
```
> Fix issues identified in SL Alpha3 Release

- websubhub-examples/kafka-hub/hub/hub_service.bal
- websubhub-examples/kafka-hub/hub/modules/connections/connections.bal
- websubhub-examples/kafka-hub/hub/modules/security/security.bal
- websubhub-examples/kafka-hub/hub/modules/util/util.bal
- websubhub-examples/kafka-hub/hub/start_hub.bal
> $subject
* Add doc-comments for connections / security / util modules.
* Fix logic issue in invoking content-notification async function.
* Here notifySubscriber async function should only be invoked when there is a new subscription. And when the Hub is restarted it should start notifySubscriber for all the persisted subscribers as well.
* When an unsubscription happens we could check whether it is available in registeredSubscribers state and cancel the previously invoked async function.
> Refactor websubhub sample

- ballerina/content_distribution.bal
- ballerina/http_service.bal
- ballerina/tests/basic_hub_test.bal
> $subject
Fixes [#1692](https://github.com/ballerina-platform/ballerina-standard-library/issues/1692)
> Add support to accept parameters for content-type header value

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
- README.md
This PR integrates the [Trivy](https://github.com/aquasecurity/trivy) vulnerability scanner for the repository file system and it will check and generate the report daily or on-demand and before the release.
Related Issue: [#1849](https://github.com/ballerina-platform/ballerina-standard-library/issues/1849)
> Add trivy scan for release builds and add daily trivy scan build

- ballerina/http_service.bal
- ballerina/hub_service.bal
- ballerina/tests/additional_error_details_test.bal
- ballerina/tests/hub_with_header_details_test.bal
- ballerina/tests/test_init.bal
- changelog.md
- gradle.properties
> $subject
Related to [#2398](https://github.com/ballerina-platform/ballerina-standard-library/issues/2398)
```ballerina
listener websubhub:Listener ls = new (9090);
service /hub on ls {
// implement remote methods
}
```
```ballerina
listener websubhub:Listener ls = new (9090);
websubhub:Service hubService = service object {
// implement remote methods
};
ls.attach(hubService, "hub");
```
```ballerina
service class HubService {
*websubhub:Service;
// implement remote methods
}
HubService hubService = new ();
ls.attach(hubService, "sub");
```
> Mark WebSubHub service-type distinct

- ballerina/tests/hub_with_readonly_params_test.bal
- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websubhub/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_19/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_19/service.bal
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_20/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_20/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/Constants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/AnalyserUtils.java
- native/src/main/java/io/ballerina/stdlib/websubhub/Constants.java
- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHttpToWebsubhubAdaptor.java
> $subject
Related to [#2604](https://github.com/ballerina-platform/ballerina-standard-library/issues/2604)
With this change, developers could use `readonly` parameters for remote methods in `websubhub:Service` declaration:
```ballerina
service /websubhub on hubListener {
isolated remote function onRegisterTopic(readonly & websubhub:TopicRegistration msg) returns websubhub:TopicRegistrationSuccess|websubhub:TopicRegistrationError {
// implement logic here
}
// implement other remote methods
}
```
`readonly` can only be applied to records declared in WebSubHub package. Hence, following will be invalid:
```ballerina
service /websubhub on hubListener {
isolated remote function onRegisterTopic(readonly & websubhub:TopicRegistration msg, readonly & http:Headers headers) returns …
```
> `readonly` support for the parameters of remote methods

- examples/kafka-hub/consolidator/consolidator_service.bal
> $subject
In kafka-hub sample, `consolidator-service` currently processes only the last event retrieved from the `poll`. But the consolidator should process all the events received from the `poll`. 
N/A
> Improve event processing logic for consolidator-service

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websubhub/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_21/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_21/main.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/ListenerInitAnalysisTask.java
> $subject
Fixes [#2815](https://github.com/ballerina-platform/ballerina-standard-library/issues/2815)
N/A
> [FIX] Compiler plugin crashes when using a new-expr with a user-defined class in the same source

- ballerina/Dependencies.toml
- ballerina/hub_client.bal
- ballerina/publisher_client.bal
- ballerina/subscription.bal
- ballerina/tests/additional_error_details_test.bal
- ballerina/tests/hub_client_test.bal
- ballerina/tests/utils_test.bal
- ballerina/topic_registration.bal
- ballerina/utils.bal
- changelog.md
> $subject
`websubhub:CommonResponse` is the base record for all the publisher client and hub client responses. 
It contains following fields:
- statusCode (Mandatory)
- mediaType (Optional)
- body (Optional)
- headers (Optional) 
Apart from a special case where one or more of the above could not be extracted from original HTTP response these fields should be populated properly.
Fixes [#2878](https://github.com/ballerina-platform/ballerina-standard-library/issues/2878)
N/A
> Populate `websubhub:CommonResponse` with all required information

- examples/kafka-hub/integration_test_suite/Ballerina.toml
- examples/kafka-hub/integration_test_suite/Cloud.toml
- examples/kafka-hub/integration_test_suite/Config.toml
- examples/kafka-hub/integration_test_suite/main.bal
- examples/kafka-hub/integration_test_suite/messages.bal
- examples/kafka-hub/integration_test_suite/subscriber_service.bal
> $subject
Part of [#3392](https://github.com/ballerina-platform/ballerina-standard-library/issues/3392) 
When running integration tests, following configurations should be updated in the `Config.toml`:
- HUB
- TOPIC
- CALLBACK_URL
- RESULTS_FILE_PATH
After running tests there will be a `result.csv` generated at `RESULTS_FILE_PATH`. It has following structure:
|Label               |Sent Count|Received Count|Status    |
|--------------------|----------|--------------|----------|
|TOPIC_REGISTRATION  |1         |1             |SUCCESSFUL|
|SUBSCRIPTION        |1         |1             |SUCCESSFUL|
|CONTENT_PUBLISH     |2         |2             |SUCCESSFUL|
|UNSUBSCRIPTION      |1         |1             |SUCCESSFUL|
|TOPIC_DEREGISTRATION|1         |1             |SUCCESSFUL|
All the …
> Add integration test-suite for azure hub deployment

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/hub_client.bal
- ballerina/tests/hub_client_test.bal
- changelog.md
> $subject
Fixes [#3564](https://github.com/ballerina-platform/ballerina-standard-library/issues/3564)
N/A
> [2201.2.x] Fix logic in `websubhub:HubClient` not to append unwanted `/` in the service-path

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websubhub/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_22/Ballerina.toml
- compiler-plugin-tests/src/test/resources/ballerina_sources/sample_22/service.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/AnalyserUtils.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/websubhub/task/ListenerInitAnalysisTask.java
> $subject
Part of [#2782](https://github.com/ballerina-platform/ballerina-standard-library/issues/2782)
N/A
> [FIX] Compiler plugin validation logic for `websubhub:Listener` args when a `check` expression is present

- examples/kafka-hub/hub/hub_service.bal
> $subject
Part of: [#4810](https://github.com/ballerina-platform/ballerina-standard-library/issues/4810)
N/A
> Add logic to retrieve kafka-consumer group from the subscription request

- examples/kafka-hub/publisher/main.bal
> $subject
- Usage:
```sh
docker run --rm --network host --name websub-publisher -e TOPIC_NAME="sample-topic" -e PAYLOAD='{"itemName":"Panasonic Trimmer","itemCode":"ITM30030","previousPrice":5000.00,"newPrice":4500.00,"currencyCode":"SEK"}' ayeshalmeida/wbsbpublisher:3.0.0
```
> [KafkaHub] Update publisher sample code with ability to provide payload as an env-variable

- examples/kafka-hub/subscriber/subscriber_service.bal
> $subject
Part of: [#5916](https://github.com/ballerina-platform/ballerina-library/issues/5916)
N/A
> [KafkaHub] Externalize websub-subscriber configurations as env-variables

- examples/kafka-hub/consolidator/Cloud.toml
- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
> $subject
Part of: [#5916](https://github.com/ballerina-platform/ballerina-library/issues/5916)
N/A
> [KafkaHub] Update docker image versions for `hub` and `consolidator`

- examples/kafka-hub/build-docker-images.sh
- examples/kafka-hub/hub/modules/persistence/persistence.bal
- examples/kafka-hub/hub/websub_subscribers.bal
> $subject
Part of: [#7376](https://github.com/ballerina-platform/ballerina-library/issues/7376)
N/A
> Incorporate support to convert Kafka headers to HTTP headers

- examples/kafka-hub/hub/modules/connections/connections.bal
- examples/kafka-hub/hub/websub_subscribers.bal
> $subject
Part of: [#7376](https://github.com/ballerina-platform/ballerina-library/issues/7376)
N/A
> Add support for parallel message-delivery

- examples/kafka-hub/A Guide on implementing Websub Hub backed by Kafka Message Broker.md
- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/hub/hub_service.bal
- examples/kafka-hub/hub/hub_state_update.bal
- examples/kafka-hub/hub/modules/connections/connections.bal
- examples/kafka-hub/hub/modules/persistence/persistence.bal
- examples/kafka-hub/hub/websub_subscribers.bal
- examples/kafka-hub/subscriber/Cloud.toml
- examples/kafka-hub/subscriber/subscriber_service.bal
> Sync the upstream with runtime fixes

- examples/kafka-hub/hub/modules/connections/connections.bal
> $subject
Related to: [#7376](https://github.com/ballerina-platform/ballerina-library/issues/7376)
N/A
> Restructure kafka-consumer paritition-offset assignment logic

- examples/kafka-hub/hub/modules/connections/connections.bal
- examples/kafka-hub/hub/websub_subscribers.bal
> $subject
Related to: [#7376](https://github.com/ballerina-platform/ballerina-library/issues/7376)
N/A
> Refactor the logic for parallel message delivery

- examples/kafka-hub/docker-compose.yaml
- examples/kafka-hub/hub/Cloud.toml
- examples/kafka-hub/hub/Config.toml
- examples/kafka-hub/hub/modules/security/security.bal
> Update package version and fix runtime issues with IdP configurations

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/http_service.bal
- ballerina/natives.bal
- ballerina/subscription.bal
> $subject
Fixes: [#7586](https://github.com/ballerina-platform/ballerina-library/issues/7586)
N/A
> Refactor subscription/unsubscription flows

- ballerina/Dependencies.toml
- ballerina/tests/basic_hub_test.bal
- ballerina/tests/hub_authentication_test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/websubhub/Constants.java
- native/src/main/java/io/ballerina/stdlib/websubhub/InteropArgs.java
- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHttpToWebsubhubAdaptor.java
- native/src/main/java/io/ballerina/stdlib/websubhub/NativeHubService.java
> $subject
Fixes: [#7600](https://github.com/ballerina-platform/ballerina-library/issues/7600)
Previously, `websubhub:Service` only supported a fixed parameter order:  
```ballerina
service /websubhub on securedListener {
remote function onRegisterTopic(websubhub:TopicRegistration message, http:Headers headers)
returns websubhub:TopicRegistrationSuccess|websubhub:TopicRegistrationError {
// logic to be executed
}
// other methods
}
```
With the latest update, parameter order in remote methods is now flexible. At runtime, parameters will be dynamically identified, allowing method signatures to be reordered. For example, the following is now valid:  
```ballerina
service /websubhub on securedListener {
remote function onRegisterTopic(http:Headers headers, websubhub:TopicRegistration …
```
> Introduce dynamic parameter order for the `websubhub:Service` remote methods
